### ISSUE TITLE
Cannot import cydnest outside the package directory

### ISSUE THREAD

**Issue by jyshangguan** [LiyrAstroph/CDNest#1]
Hi Yanrong,

    After the installation, the demo works fine when I run it in the package directory.  However, when I try to import cydnest at a different directory than the package directory, I got the following error:
`Traceback (most recent call last):
  File "gauss.py", line 9, in <module>
    import cydnest
ImportError: dlopen(/Users/shangguan/Softwares/CDNest/cydnest.cpython-37m-darwin.so, 2): Library not loaded: libdnest.so
  Referenced from: /Users/shangguan/Softwares/CDNest/cydnest.cpython-37m-darwin.so
  Reason: image not found`

Did I miss to export some link in `bashrc`?

**Comment by liyropt** [comment]
yes, in bashrc, add a line to export "path to libdnest.so" to LD_LIBRARY_PATH as

export LD_LIBRARY_PATH=/path/to/libdnest.so:$LD_LIBRARY_PATH

Do not forget to execute "source .bashrc"

**Comment by jyshangguan** [comment]
The LD_LIBRARY_PATH was already added.  I redo the `source .bashrc`, but the error still occurs...

**Comment by liyropt** [comment]
solved.
